[build]
  command = "npm run build"
  functions = ".netlify/functions-internal"
  publish = "build/client"

[dev]
  command = "npm run dev"
  port = 3000

[[headers]]
  for = "/assets/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[functions]
  node_bundler = "esbuild" 